apiVersion: v2
name: rapidfort
description: RapidFort Big Bang Helm Chart
type: application
version: 1.2.5-bb.14
appVersion: 1.1.300
dependencies:
  - name: gluon
    version: "0.5.15"
    repository: "oci://registry1.dso.mil/bigbang"
annotations:
  bigbang.dev/upstreamReleaseNotesMarkdown: ""
