{{- /*
  Copyright RapidFort, Inc.
*/}}
{{- if .Values.fileupload.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileupload
  labels:
    app.kubernetes.io/name: fileupload
spec:
  replicas: {{ .Values.fileupload.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: fileupload
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fileupload
    spec:
      {{- if .Values.fileupload.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.fileupload.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.fileupload.volumes }}
      volumes:
        {{- tpl (toYaml (index .Values.fileupload.volumes )) . | nindent 8 }}
      {{- end }}
      {{- if .Values.fileupload.ephemeralVolumeClaimTemplates }}
      {{- if not .Values.fileupload.volumes }}
      volumes:
      {{- end }}
      {{- range .Values.fileupload.ephemeralVolumeClaimTemplates -}}
          {{ (tpl (include "rapidfort-platform.singleEphemeralVolumeClaim" .) $) | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.fileupload.initContainers }}
      initContainers:
        {{- toYaml (index .Values.fileupload.initContainers ) | nindent 8 }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccount: {{ include "rapidfort-platform.serviceAccountName" . }}
      serviceAccountName: {{ include "rapidfort-platform.serviceAccountName" . }}
      {{- end }}      
      containers:
        - name: fileupload
          {{- if .Values.fileupload.containerSecurityContext }}
          securityContext: {{- toYaml .Values.fileupload.containerSecurityContext | nindent 12 }}
          {{- end }}
          image: {{ .Values.fileupload.image }}
          imagePullPolicy: IfNotPresent
          {{- if .Values.fileupload.volumeMounts }}
          volumeMounts:
            {{- toYaml (index .Values.fileupload.volumeMounts ) | nindent 12 }}
          {{- end }}
          {{- if .Values.fileupload.ports }}
          ports: {{- toYaml .Values.fileupload.ports | nindent 12 }}
          {{- end }}
          {{- if or $.Values.fileupload.envVars $.Values.fileupload.envVarsSecret }}
          env:
            {{- range $key, $value := $.Values.fileupload.envVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range .Values.fileupload.envVarsSecret }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: rapidfort-secret
                  key: {{ . }}
            {{- end }}
          {{- end }}
          {{- if .Values.fileupload.resources}}
          resources:
            {{- toYaml .Values.fileupload.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.fileupload.startupProbe}}
          startupProbe:
            {{- toYaml .Values.fileupload.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.fileupload.livenessProbe}}
          livenessProbe:
            {{- toYaml .Values.fileupload.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.fileupload.readinessProbe}}
          readinessProbe:
            {{- toYaml .Values.fileupload.readinessProbe | nindent 12 }}
          {{- end }}
      {{- with .Values.fileupload.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fileupload.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fileupload.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: fileupload
  labels:
    app.kubernetes.io/name: fileupload
spec:
  type: {{ .Values.fileupload.service.type }}
  ports:
    - port: {{ .Values.fileupload.service.port }}
      protocol: TCP
      name: http
      targetPort: {{ .Values.fileupload.service.targetPort }}
  selector:
    app.kubernetes.io/name: fileupload
{{- if .Values.global.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fileupload
  labels:
    app.kubernetes.io/name: fileupload
  annotations:
  {{- with .Values.fileupload.ingress.annotations }}  
    {{- toYaml . | nindent 4 }}  
  {{- end }}
  {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }} 
spec:
  ingressClassName: {{ default .Values.fileupload.ingress.ingressClassName .Values.global.ingress.className }}
  {{- if .Values.global.ingress.tls }}
    {{ include "rapidfort-platform.ingress.tls" . | nindent 2 }}
  {{- end }}
  rules:
    {{- range .Values.fileupload.ingress.hosts }}
    - host: {{ include "prefix.isFQDN" $.Values.global.hostname | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: fileupload
                port:
                  number: {{ $.Values.fileupload.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}