{{- /*
  Copyright RapidFort, Inc.
*/}}
{{- if .Values.frontrow.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontrow
  labels:
    app.kubernetes.io/name: frontrow
spec:
  replicas: {{ .Values.frontrow.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: frontrow
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontrow
    spec:
      {{- if .Values.frontrow.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.frontrow.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.frontrow.volumes }}
      volumes:
        {{- tpl (toYaml (index .Values.frontrow.volumes )) . | nindent 8 }}
      {{- end }}
      {{- if .Values.frontrow.initContainers }}
      initContainers:
        {{- toYaml (index .Values.frontrow.initContainers ) | nindent 8 }}
      {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml (index .Values.global.imagePullSecrets ) | nindent 8 }}      
      {{- end }}
      containers:
        - name: frontrow
          {{- if .Values.frontrow.containerSecurityContext }}
          securityContext: {{- toYaml .Values.frontrow.containerSecurityContext | nindent 12 }}
          {{- end }}
          image: {{ .Values.frontrow.image }}
          imagePullPolicy: IfNotPresent
          {{- if .Values.frontrow.volumeMounts }}
          volumeMounts:
            {{- toYaml (index .Values.frontrow.volumeMounts ) | nindent 12 }}
          {{- end }}
          {{- if .Values.frontrow.ports }}
          ports: {{- toYaml .Values.frontrow.ports | nindent 12 }}
          {{- end }}
          {{- if or $.Values.frontrow.envVars $.Values.frontrow.envVarsSecret }}
          env:
            {{- range $key, $value := $.Values.frontrow.envVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range .Values.frontrow.envVarsSecret }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: rapidfort-secret
                  key: {{ . }}
            {{- end }}
          {{- end }}
          {{- if .Values.frontrow.resources}}
          resources:
            {{- toYaml .Values.frontrow.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.frontrow.startupProbe}}
          startupProbe:
            {{- toYaml .Values.frontrow.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.frontrow.livenessProbe}}
          livenessProbe:
            {{- toYaml .Values.frontrow.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.frontrow.readinessProbe}}
          readinessProbe:
            {{- toYaml .Values.frontrow.readinessProbe | nindent 12 }}
          {{- end }}
      {{- with .Values.frontrow.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontrow.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontrow.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontrow
  labels:
    app.kubernetes.io/name: frontrow
spec:
  type: {{ .Values.frontrow.service.type }}
  ports:
    - port: {{ .Values.frontrow.service.port }}
      protocol: TCP
      name: http
      targetPort: {{ .Values.frontrow.service.targetPort }}
  selector:
    app.kubernetes.io/name: frontrow
{{- if .Values.global.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontrow
  labels:
    app.kubernetes.io/name: frontrow
  annotations:
  {{- with .Values.frontrow.ingress.annotations }}  
    {{- toYaml . | nindent 4 }}  
  {{- end }}
  {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }} 
spec:
  ingressClassName: {{ default .Values.frontrow.ingress.ingressClassName .Values.global.ingress.className }}
  {{- if .Values.global.ingress.tls }}
    {{ include "rapidfort-platform.ingress.tls" . | nindent 2 }}
  {{- end }}
  rules:
    {{- range .Values.frontrow.ingress.hosts }}
    - host: {{ include "prefix.isFQDN" $.Values.global.hostname | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: frontrow
                port:
                  number: {{ $.Values.frontrow.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}