{{- /*
  Copyright RapidFort, Inc.
*/}}
{{- if .Values.rfapi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rfapi
  labels:
    app.kubernetes.io/name: rfapi
spec:
  replicas: {{ .Values.rfapi.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: rfapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rfapi
    spec:
      {{- if .Values.rfapi.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.rfapi.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.rfapi.volumes }}
      volumes:
        {{- tpl (toYaml (index .Values.rfapi.volumes )) . | nindent 8 }}
      {{- end }}
      {{- if .Values.rfapi.initContainers }}
      initContainers:
        {{- toYaml (index .Values.rfapi.initContainers ) | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccount: {{ include "rapidfort-platform.serviceAccountName" . }}
      serviceAccountName: {{ include "rapidfort-platform.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}      
      containers:
        - name: rfapi
          {{- if .Values.rfapi.containerSecurityContext }}
          securityContext: {{- toYaml .Values.rfapi.containerSecurityContext | nindent 12 }}
          {{- end }}
          image: {{ .Values.rfapi.image }}
          imagePullPolicy: IfNotPresent
          {{- if .Values.rfapi.volumeMounts }}
          volumeMounts:
            {{- toYaml (index .Values.rfapi.volumeMounts ) | nindent 12 }}
          {{- end }}
          {{- if .Values.rfapi.ports }}
          ports: {{- toYaml .Values.rfapi.ports | nindent 12 }}
          {{- end }}
          {{- if or $.Values.rfapi.envVars $.Values.rfapi.envVarsSecret }}
          env:
            {{- range $key, $value := $.Values.rfapi.envVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range .Values.rfapi.envVarsSecret }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: rapidfort-secret
                  key: {{ . }}
            {{- end }}
          {{- end }}
          {{- if .Values.rfapi.resources}}
          resources:
            {{- toYaml .Values.rfapi.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.rfapi.startupProbe}}
          startupProbe:
            {{- toYaml .Values.rfapi.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.rfapi.livenessProbe}}
          livenessProbe:
            {{- toYaml .Values.rfapi.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.rfapi.readinessProbe}}
          readinessProbe:
            {{- toYaml .Values.rfapi.readinessProbe | nindent 12 }}
          {{- end }}
      {{- with .Values.rfapi.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rfapi.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rfapi.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: rfapi
  labels:
    app.kubernetes.io/name: rfapi
spec:
  type: {{ .Values.rfapi.service.type }}
  ports:
    - port: {{ .Values.rfapi.service.port }}
      protocol: TCP
      name: http
      targetPort: {{ .Values.rfapi.service.targetPort }}
  selector:
    app.kubernetes.io/name: rfapi
{{- if .Values.global.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rfapi-http
  labels:
    app.kubernetes.io/name: rfapi
  annotations:
    {{- with .Values.rfapi.ingress.http.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.global.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ default .Values.rfapi.ingress.ingressClassName .Values.global.ingress.className }}
  {{- if .Values.global.ingress.tls }}
    {{ include "rapidfort-platform.ingress.tls" . | nindent 2 }}
  {{- end }}
  rules:
    {{- range .Values.rfapi.ingress.http.hosts }}
    - host: {{ include "prefix.isFQDN" $.Values.global.hostname | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: rfapi
                port:
                  number: {{ $.Values.rfapi.service.port }}
          {{- end }}
    {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rfapi-websocket
  labels:
    app.kubernetes.io/name: rfapi
  annotations:
  {{- with .Values.rfapi.ingress.websocket.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ default .Values.rfapi.ingress.ingressClassName .Values.global.ingress.className }}
  {{- if .Values.global.ingress.tls }}
    {{ include "rapidfort-platform.ingress.tls" . | nindent 2 }}
  {{- end }}
  rules:
    {{- range .Values.rfapi.ingress.websocket.hosts }}
    - host: {{ include "prefix.isFQDN" $.Values.global.hostname | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: rfapi
                port:
                  number: {{ $.Values.rfapi.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}