{{- /*
  Copyright RapidFort, Inc.
*/}}
{{- if .Values.rfpubsub.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rfpubsub
  labels:
    app.kubernetes.io/name: rfpubsub
    app.kubernetes.io/instance: rfpubsub
    app.kubernetes.io/version: "{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.rfpubsub.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: rfpubsub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rfpubsub
        app.kubernetes.io/instance: rfpubsub
        app.kubernetes.io/version: "{{ .Chart.Version }}"
    spec:
      {{- if .Values.rfpubsub.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.rfpubsub.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.rfpubsub.volumes }}
      volumes:
        {{- tpl (toYaml (index .Values.rfpubsub.volumes )) . | nindent 8 }}
      {{- end }}
      {{- if .Values.rfpubsub.initContainers }}
      initContainers:
        {{- toYaml (index .Values.rfpubsub.initContainers ) | nindent 8 }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccount: {{ include "rapidfort-platform.serviceAccountName" . }}
      serviceAccountName: {{ include "rapidfort-platform.serviceAccountName" . }}
      {{- end }}
      {{- if .Values.rfpubsub.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.rfpubsub.terminationGracePeriodSeconds }}
      {{- end }}      
      containers:
        - name: rfpubsub
          {{- if .Values.rfpubsub.containerSecurityContext }}
          securityContext: {{- toYaml .Values.rfpubsub.containerSecurityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.rfpubsub.image.repository }}:{{ .Values.rfpubsub.image.tag }}"
          imagePullPolicy: IfNotPresent
          {{- if .Values.rfpubsub.volumeMounts }}
          volumeMounts:
            {{- toYaml (index .Values.rfpubsub.volumeMounts ) | nindent 12 }}
          {{- end }}
          {{- if .Values.rfpubsub.ports }}
          ports: {{- toYaml .Values.rfpubsub.ports | nindent 12 }}
          {{- end }}
          {{- if or $.Values.rfpubsub.envVars $.Values.rfpubsub.envVarsSecret }}
          env:
            {{- range $key, $value := $.Values.rfpubsub.envVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range .Values.rfpubsub.envVarsSecret }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: rapidfort-secret
                  key: {{ . }}
            {{- end }}
          {{- end }}
          {{- if .Values.rfpubsub.resources}}
          resources:
            {{- toYaml .Values.rfpubsub.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.rfpubsub.startupProbe}}
          startupProbe:
            {{- toYaml .Values.rfpubsub.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.rfpubsub.livenessProbe}}
          livenessProbe:
            {{- toYaml .Values.rfpubsub.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.rfpubsub.readinessProbe}}
          readinessProbe:
            {{- toYaml .Values.rfpubsub.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.rfpubsub.lifecycle }}
          lifecycle:
            {{- toYaml .Values.rfpubsub.lifecycle | nindent 12 }}
          {{- end }}          
      {{- with .Values.rfpubsub.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        {{- with .Values.rfpubsub.affinity.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}       
        podAntiAffinity:
          {{- if eq .Values.rfpubsub.affinity.antiAffinity "strict" }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: rfpubsub
              topologyKey: "kubernetes.io/hostname"  
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: rfpubsub
                topologyKey: "kubernetes.io/hostname"
          {{- end }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: rfpubsub
      {{- with .Values.rfpubsub.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: rfpubsub
  labels:
    app.kubernetes.io/name: rfpubsub
spec:
  type: {{ .Values.rfpubsub.service.type }}
  ports:
    - port: {{ .Values.rfpubsub.service.port }}
      protocol: TCP
      name: http
      targetPort: {{ .Values.rfpubsub.service.targetPort }}
  selector:
    app.kubernetes.io/name: rfpubsub
{{- if .Values.global.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rfpubsub
  labels:
    app.kubernetes.io/name: rfpubsub
  annotations:
  {{- with .Values.rfpubsub.ingress.annotations }}  
    {{- toYaml . | nindent 4 }}  
  {{- end }}
  {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }} 
spec:
  ingressClassName: {{ default .Values.rfpubsub.ingress.ingressClassName .Values.global.ingress.className }}
  {{- if .Values.global.ingress.tls }}
    {{ include "rapidfort-platform.ingress.tls" . | nindent 2 }}
  {{- end }}
  rules:
    {{- range .Values.rfpubsub.ingress.hosts }}
    - host: {{ include "prefix.isFQDN" $.Values.global.hostname | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: rfpubsub
                port:
                  number: {{ $.Values.rfpubsub.service.port }}
          {{- end }}
    {{- end }}
  {{- if not (include "prefix.isIPAddress" $.Values.global.hostname ) -}}
    {{- range .Values.rfpubsub.ingress.hosts }}
    - host:
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: rfpubsub
                port:
                  number: {{ $.Values.rfpubsub.service.port }}
          {{- end }}
    {{- end }}
  {{- end -}}
{{- end }}
---
{{- if .Values.rfpubsub.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rfpubsub
  labels:
    app.kubernetes.io/name: rfpubsub
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rfpubsub
  minReplicas: {{ .Values.rfpubsub.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.rfpubsub.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.rfpubsub.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: "Utilization"
          averageUtilization: {{ .Values.rfpubsub.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.rfpubsub.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: "Utilization"
          averageUtilization: {{ .Values.rfpubsub.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}