{{- /*
  Copyright RapidFort, Inc.
*/}}
{{- if .Values.runner.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runnerbeat
  labels:
    app.kubernetes.io/name: runnerbeat
    app.kubernetes.io/instance: runnerbeat
    app.kubernetes.io/version: "{{ .Chart.Version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: runnerbeat
  template:
    metadata:
      labels:
        app.kubernetes.io/name: runnerbeat
        app.kubernetes.io/instance: runnerbeat
        app.kubernetes.io/version: "{{ .Chart.Version }}"
    spec:
      {{- if .Values.runner.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.runner.podSecurityContext | nindent 8 }}
      {{- end }}
      volumes:      
      {{- if .Values.runner.volumes }}
        {{- tpl (toYaml (index .Values.runner.volumes )) . | nindent 8 }}
      {{- end }}
      {{- if .Values.runner.ephemeralVolumeClaimTemplates }}
      {{- range .Values.runner.ephemeralVolumeClaimTemplates -}}
          {{ (tpl (include "rapidfort-platform.singleEphemeralVolumeClaim" .) $) | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.db.ssl }}
        {{- if .Values.db.ssl.certFile }}
          {{- (tpl (include "rapidfort-platform.db_ssl_cert_volume" .Values.db.ssl ) .)| nindent 8 }}
        {{- end }}
      {{- end }}      
      {{- if .Values.runner.initContainers }}
      initContainers:
        {{- toYaml (index .Values.runner.initContainers ) | nindent 8 }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccount: {{ include "rapidfort-platform.serviceAccountName" . }}
      serviceAccountName: {{ include "rapidfort-platform.serviceAccountName" . }}
      {{- end }}      
      containers:
        - name: runner
          {{- if .Values.runner.containerSecurityContext }}
          securityContext: {{- toYaml .Values.runner.containerSecurityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.runner.image.repository }}:{{ .Values.runner.image.tag }}"
          imagePullPolicy: IfNotPresent
          volumeMounts:          
          {{- if .Values.runner.volumeMounts }}
            {{- toYaml (index .Values.runner.volumeMounts ) | nindent 12 }}
          {{- end }}
          {{- if .Values.db.ssl }}
            {{- if .Values.db.ssl.certFile }}
              {{- tpl (include "rapidfort-platform.db_ssl_cert_volumeMount" .Values.db.ssl ) $ | nindent 12 }}
            {{- end }}
          {{- end }}               
          {{- if .Values.runner.ports }}
          env:
            # disable rf installation due to not running as root.
            - name: INSTALL_RF_CLI
              value: "false"
            - name: RUNNER_BEAT_MODE
              value: "1"
            {{- range $key, $value := $.Values.runner.envVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range .Values.runner.envVarsSecret }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: rapidfort-secret
                  key: {{ . }}
            {{- end }}
          {{- end }}
          {{- if .Values.runner.resources}}
          resources:
            {{- toYaml .Values.runner.resources | nindent 12 }}
          {{- end }}
      {{- with .Values.runner.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.runner.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.runner.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
