{{- /*
  Copyright RapidFort, Inc.
*/}}
{{- if .Values.runnerbeat.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runnerbeat
  labels:
    app.kubernetes.io/name: runnerbeat
    app.kubernetes.io/instance: runnerbeat
    app.kubernetes.io/version: "{{ .Chart.Version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: runnerbeat
  template:
    metadata:
      labels:
        app.kubernetes.io/name: runnerbeat
        app.kubernetes.io/instance: runnerbeat
        app.kubernetes.io/version: "{{ .Chart.Version }}"
    spec:
      {{- if .Values.runnerbeat.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.runnerbeat.podSecurityContext | nindent 8 }}
      {{- end }}
      volumes:      
      {{- if .Values.runnerbeat.volumes }}
        {{- tpl (toYaml (index .Values.runnerbeat.volumes )) . | nindent 8 }}
      {{- end }}
      {{- if .Values.runnerbeat.ephemeralVolumeClaimTemplates }}
      {{- range .Values.runnerbeat.ephemeralVolumeClaimTemplates -}}
          {{ (tpl (include "rapidfort-platform.singleEphemeralVolumeClaim" .) $) | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.db.ssl }}
        {{- if .Values.db.ssl.certFile }}
          {{- (tpl (include "rapidfort-platform.db_ssl_cert_volume" .Values.db.ssl ) .)| nindent 8 }}
        {{- end }}
      {{- end }}      
      {{- if .Values.runnerbeat.initContainers }}
      initContainers:
        {{- toYaml (index .Values.runnerbeat.initContainers ) | nindent 8 }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccount: {{ include "rapidfort-platform.serviceAccountName" . }}
      serviceAccountName: {{ include "rapidfort-platform.serviceAccountName" . }}
      {{- end }}      
      containers:
        - name: runner
          {{- if .Values.runnerbeat.containerSecurityContext }}
          securityContext: {{- toYaml .Values.runnerbeat.containerSecurityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.runnerbeat.image.repository }}:{{ .Values.runnerbeat.image.tag }}"
          imagePullPolicy: IfNotPresent
          volumeMounts:          
          {{- if .Values.runnerbeat.volumeMounts }}
            {{- toYaml (index .Values.runnerbeat.volumeMounts ) | nindent 12 }}
          {{- end }}
          {{- if .Values.db.ssl }}
            {{- if .Values.db.ssl.certFile }}
              {{- tpl (include "rapidfort-platform.db_ssl_cert_volumeMount" .Values.db.ssl ) $ | nindent 12 }}
            {{- end }}
          {{- end }}               
          {{- if .Values.runnerbeat.ports }}
          env:
            # disable rf installation due to not running as root.
            - name: INSTALL_RF_CLI
              value: "false"
            - name: RUNNER_BEAT_MODE
              value: "1"
            {{- range $key, $value := $.Values.runnerbeat.envVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range .Values.runnerbeat.envVarsSecret }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: rapidfort-secret
                  key: {{ . }}
                  optional: true
            {{- end }}
          {{- end }}
          {{- if .Values.runnerbeat.resources}}
          resources:
            {{- toYaml .Values.runnerbeat.resources | nindent 12 }}
          {{- end }}
      {{- with .Values.runnerbeat.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        {{- with .Values.runnerbeat.affinity.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}       
        podAntiAffinity:
          {{- if eq .Values.runnerbeat.affinity.antiAffinity "strict" }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: runnerbeat
              topologyKey: "kubernetes.io/hostname"  
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: runnerbeat
                topologyKey: "kubernetes.io/hostname"
          {{- end }}
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: runnerbeat
      {{- with .Values.runnerbeat.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
