{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-aws-ses
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: 
    matchLabels:
      app.kubernetes.io/name: backend
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 587
      protocol: TCP
{{- end }}
