{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-vulns-db-external
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: 
    matchLabels:
      app.kubernetes.io/name: vulnsdb
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock: 
        cidr: {{ default "0.0.0.0/0" .Values.networkPolicies.controlPlaneCidr }}
    ports:
    - port: 443
      protocol: TCP
{{- end }}