{{- if and .Values.networkPolicies.enabled .Values.istio.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-istio
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          {{- toYaml .Values.networkPolicies.ingress.namespaceLabels | default "{}" | nindent 10}}
      podSelector:
        matchLabels:
          {{- toYaml .Values.networkPolicies.ingressLabels | nindent 10}}
    ports:
    - port: 8080
      protocol: TCP
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          {{- toYaml .Values.networkPolicies.egress.namespaceLabels | default "{}" | nindent 10}}
      podSelector:
        matchLabels:
          istio: pilot
{{- end }}
