{{ if .Values.networkPolicies.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: allow-rf-community
  namespace: {{ .Release.Namespace }}
spec:
  hosts: 
  #TODO: update to values.yaml reference
  - us01.rapidfort.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: allow-aws
  namespace: {{ .Release.Namespace }}
spec:
  hosts: 
  - "*.amazonaws.com"
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  # resolution: DNS
  location: MESH_EXTERNAL
# ---
# {{ if not .Values.mysql.enabled }}
# apiVersion: networking.istio.io/v1beta1
# kind: ServiceEntry
# metadata:
#   name: allow-external-rds
#   namespace: {{ .Release.Namespace }}
# spec:
#   hosts:
#   - {{ .Values.global.db.auth.host }}
#   ports:
#   - number: {{ .Values.global.db.auth.port }}
#     name: mysql
#     protocol: TCP
#   resolution: DNS
#   location: MESH_EXTERNAL
# {{ end }}
{{ end }} 
