{{ if .Values.networkPolicies.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: allow-vuln-db
  namespace: {{ .Release.Namespace }}
spec:
  hosts: 
  - {{ .Values.vulnsdb.envVars.RFVDB_HOST }}
  exportTo:
    - .
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: allow-aws
  namespace: {{ .Release.Namespace }}
spec:
  hosts: 
  - "*.amazonaws.com"
  exportTo:
    - .
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  # resolution: DNS
  location: MESH_EXTERNAL
---
{{ if not .Values.mysql.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: allow-external-rds
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.db.auth.host }}
  exportTo:
    - .
  ports:
  - number: {{ .Values.db.auth.port }}
    name: mysql
    protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
{{ end }}
{{ end }} 
