{{- /*
  Copyright RapidFort, Inc.
*/}}
{{- if .Values.keycloak.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
spec:
  replicas: {{ .Values.keycloak.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
    spec:
      {{- if .Values.keycloak.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.keycloak.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.keycloak.volumes }}
      volumes:
        {{- tpl (toYaml (index .Values.keycloak.volumes )) . | nindent 8 }}
      {{- end }}
      {{- if .Values.keycloak.initContainers }}
      initContainers:
        {{- toYaml (index .Values.keycloak.initContainers ) | nindent 8 }}
      {{- end }}      
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: keycloak
          {{- if .Values.keycloak.containerSecurityContext }}
          securityContext: {{- toYaml .Values.keycloak.containerSecurityContext | nindent 12 }}
          {{- end }}
          image: {{ .Values.keycloak.image }}
          imagePullPolicy: IfNotPresent
          {{- if .Values.keycloak.volumeMounts }}
          volumeMounts:
            {{- toYaml (index .Values.keycloak.volumeMounts ) | nindent 12 }}
          {{- end }}
          {{- if .Values.keycloak.ports }}
          ports: {{- toYaml .Values.keycloak.ports | nindent 12 }}
          {{- end }}
          {{- if or $.Values.keycloak.envVars $.Values.keycloak.envVarsSecret }}
          env:
            {{- range $key, $value := $.Values.keycloak.envVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range .Values.keycloak.envVarsSecret }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: rapidfort-secret
                  key: {{ . }}
            {{- end }}
          {{- end }}
          {{- if .Values.keycloak.resources}}
          resources:
            {{- toYaml .Values.keycloak.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.keycloak.startupProbe}}
          startupProbe:
            {{- toYaml .Values.keycloak.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.keycloak.livenessProbe}}
          livenessProbe:
            {{- toYaml .Values.keycloak.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.keycloak.readinessProbe}}
          readinessProbe:
            {{- toYaml .Values.keycloak.readinessProbe | nindent 12 }}
          {{- end }}
      {{- with .Values.keycloak.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.keycloak.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.keycloak.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
    - port: {{ .Values.keycloak.service.port }}
      protocol: TCP
      name: http
      targetPort: {{ .Values.keycloak.service.targetPort }}
  selector:
    app.kubernetes.io/name: keycloak
# Option to enable ingress when there is something to debug with KeyCloak service.    
{{- if .Values.keycloak.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
  {{- with .Values.keycloak.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ default .Values.keycloak.ingress.className .Values.global.ingress.className }}
  rules:
    {{- range .Values.keycloak.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: keycloak
                port:
                  number: {{ $.Values.keycloak.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}