{{- /*
  Copyright RapidFort, Inc.
*/}}
{{- if .Values.lockredis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lock-redis
  labels:
    app.kubernetes.io/name: lock-redis
spec:
  serviceName: lock-redis
  replicas: {{ .Values.lockredis.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: lock-redis    
  {{- if .Values.lockredis.volumeClaimTemplates }}
  volumeClaimTemplates:
  {{- range .Values.lockredis.volumeClaimTemplates -}}
      {{ include "rapidfort-platform.singleVolumeClaim" . | nindent 2 }}
  {{- end }}
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lock-redis
    spec:
      {{- if .Values.lockredis.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.lockredis.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.lockredis.volumes }}
      volumes:
        {{- tpl (toYaml (index .Values.lockredis.volumes )) . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: disk-init
        image: registry1.dso.mil/ironbank/redhat/ubi/ubi8-minimal:8.9
        command: ["chown", "1001", "/opt/rapidfort/local-bucket/data/lock-redis"]
        volumeMounts:
          - name: redis-data
            mountPath: /opt/rapidfort/local-bucket/data/lock-redis
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecrets }}
      {{- end }}
      containers:
        - name: lock-redis
          {{- if .Values.lockredis.containerSecurityContext }}
          securityContext: {{- toYaml .Values.lockredis.containerSecurityContext | nindent 12 }}
          {{- end }}
          image: {{ .Values.lockredis.image }}
          imagePullPolicy: IfNotPresent
          {{- if .Values.lockredis.volumeMounts }}
          volumeMounts:
            {{- toYaml (index .Values.lockredis.volumeMounts ) | nindent 12 }}
          {{- end }}
          {{- if .Values.lockredis.ports }}
          ports: {{- toYaml .Values.lockredis.ports | nindent 12 }}
          {{- end }}
          {{- if or $.Values.lockredis.envVars $.Values.lockredis.envVarsSecret }}
          env:
            {{- range $key, $value := $.Values.lockredis.envVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range .Values.lockredis.envVarsSecret }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: rapidfort-secret
                  key: {{ . }}
            {{- end }}
          {{- end }}
          {{- if .Values.lockredis.resources}}
          resources:
            {{- toYaml .Values.lockredis.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.lockredis.startupProbe}}
          startupProbe:
            {{- toYaml .Values.lockredis.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.lockredis.livenessProbe}}
          livenessProbe:
            {{- toYaml .Values.lockredis.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.lockredis.readinessProbe}}
          readinessProbe:
            {{- toYaml .Values.lockredis.readinessProbe | nindent 12 }}
          {{- end }}
      {{- with .Values.lockredis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lockredis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lockredis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: lock-redis
  labels:
    app.kubernetes.io/name: lock-redis
spec:
  type: {{ .Values.lockredis.service.type }}
  ports:
    - port: {{ .Values.lockredis.service.port }}
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: lock-redis
{{- end }}
