{{- /*
  Copyright RapidFort, Inc.
*/}}
{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
spec:
  serviceName: redis
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: redis   
  {{- if .Values.redis.volumeClaimTemplates }}
  volumeClaimTemplates:
  {{- range .Values.redis.volumeClaimTemplates -}}
      {{ (tpl ( include "rapidfort-platform.singleVolumeClaim" .) $) | nindent 2 }}
  {{- end }}
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
    spec:
      {{- if .Values.redis.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.redis.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.redis.volumes }}
      volumes:
        {{- tpl (toYaml (index .Values.redis.volumes )) . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: disk-init
        image: registry1.dso.mil/ironbank/redhat/ubi/ubi8-minimal:8.9
        command: ["chown", "1001", "/opt/rapidfort/local-bucket/data/redis"]
        volumeMounts:
          - name: redis-data
            mountPath: /opt/rapidfort/local-bucket/data/redis
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecrets }}
      {{- end }}
      containers:
        - name: redis
          {{- if .Values.redis.containerSecurityContext }}
          securityContext: {{- toYaml .Values.redis.containerSecurityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.redis.image }}"
          {{- if .Values.redis.command }}
          command: {{- toYaml .Values.redis.command | nindent 12 }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          {{- if .Values.redis.volumeMounts }}
          volumeMounts:
            {{- toYaml (index .Values.redis.volumeMounts ) | nindent 12 }}
          {{- end }}
          {{- if .Values.redis.ports }}
          ports: {{- toYaml .Values.redis.ports | nindent 12 }}
          {{- end }}
          {{- if or $.Values.redis.envVars $.Values.redis.envVarsSecret }}
          env:
            {{- range $key, $value := $.Values.redis.envVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range .Values.redis.envVarsSecret }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: rapidfort-secret
                  key: {{ . }}
            {{- end }}
          {{- end }}
          {{- if .Values.redis.resources}}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.redis.startupProbe}}
          startupProbe:
            {{- toYaml .Values.redis.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.redis.livenessProbe}}
          livenessProbe:
            {{- toYaml .Values.redis.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.redis.readinessProbe}}
          readinessProbe:
            {{- toYaml .Values.redis.readinessProbe | nindent 12 }}
          {{- end }}
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: redis
{{- end }}
