{{- if .Values.rfsupportServiceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ default "false" .Values.rfsupportServiceAccount.automountServiceAccountToken }}
metadata:
  name: {{ include "rapidfort-platform.rfsupportServiceAccountName" . }}
  labels:
    {{- include "rapidfort-platform.labels" . | nindent 4 }}
  {{- with .Values.rfsupportServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
