{{- if and (not .Values.mysql.enabled) .Values.mysql.seedDatabase }}
apiVersion: batch/v1
kind: Job
metadata:
  name: external-db-seed
  annotations:
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      imagePullSecrets:
      {{- range .Values.mysql.image.pullSecrets }}
      {{- printf "- name: %s" . | nindent 8 }}
      {{- end }}
      containers:
      - name: external-mysql-seed
        image: "{{ .Values.mysql.image.registry }}/{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        command:
          - "/bin/sh"
          - "-c"
          # - "mysql --host={{ .Values.mysql.mysqlServer}} --user=root --password={{ .Values.mysql.auth.rootPassword }} < /data/init.sql"
          - sleep 3600
        volumeMounts:
        - name: init-config
          mountPath: /data
      volumes:
      - name: init-config
        configMap:
          name: init-db-configuration
      restartPolicy: Never
{{- end}}