{{- if or (index .Values "iso-master" "enabled") (index .Values "rf-scan" "enabled") }}
# adding conditional to prevent helmrelease from hanging due to pending PVC's
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:   
  name: image-db-pvc
spec:
  resources:
    requests:
      storage: 1Gi   
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:   
  name: package-analyzer-db-pvc
spec:
  resources:
    requests:
      storage: 1Gi   
  accessModes:
  - ReadWriteOnce
{{- end }}