apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:   
  name: image-db-pvc
spec:
  resources:
    requests:
      storage: 1Gi   
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:   
  name: package-analyzer-db-pvc
spec:
  resources:
    requests:
      storage: 1Gi   
  accessModes:
  - ReadWriteOnce