{{ if and .Values.redis.enabled .Values.redis.svcWorkaround }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "rapidfort.labels" . | nindent 4 }}
  name: redis
  namespace: {{ .Release.Namespace | quote }}
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: tcp-redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: {{ .Release.Namespace | quote }}
    app.kubernetes.io/name: redis
  type: ClusterIP
status:
  loadBalancer: {}
{{ end }}