apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "rapidfort-platform.serviceAccountName" . }}
  namespace: {{ .Release.namespace }}
rules:
- apiGroups:
  - '*'
  resources:
  - pods
  verbs:
  - 'get'
  - 'list'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rapidfort-platform.serviceAccountName" . }}
  namespace: {{ .Release.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "rapidfort-platform.serviceAccountName" . }}
  namespace: {{ .Release.namespace }}
roleRef:
  kind: Role
  name: {{ include "rapidfort-platform.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io