apiVersion: v1
kind: Secret
metadata:
  name: rf-secret
{{- with .Values.secrets.stringData }}
stringData:
  {{- range $key, $value := . }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 2 }}
  {{- end }}
{{- end }}
  {{- if .Values.mysql.enabled }}
  {{- printf "DB_URL: %s" (printf "mysql://%s:%s@mysql/standalone" .Values.mysql.auth.username .Values.mysql.auth.password | quote) | nindent 2}}
  {{- else }}
  {{- printf "DB_URL: %s" (printf "mysql://%s:%s@%s/standalone" .Values.mysql.auth.username .Values.mysql.auth.password .Values.mysql.mysqlServer | quote) | nindent 2 }}
  {{- end }}