apiVersion: v1
kind: Secret
metadata:
  name: rf-secret
{{- with .Values.secrets.stringData }}
stringData:
  {{- range $key, $value := . }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 2 }}
  {{- end }}
{{- end }}