apiVersion: v1
kind: Secret
metadata:
  name: rapidfort-secret
type: "Opaque"
data:
  {{- if and .Values.global.type (eq .Values.global.type "SAAS") }}
  DEPLOY_MODE: {{ "SAAS" | b64enc | quote }}
  RF_APP_HOST: {{ default "" .Values.global.hostname | b64enc | quote }}
  RF_APP_ADMIN: {{ default "" .Values.global.hostname | b64enc | quote }}
  RF_APP_ADMIN_PASSWD: {{ default "" .Values.global.hostname | b64enc | quote }}
  {{- else }}
  DEPLOY_MODE: {{ "STANDALONE" | b64enc | quote }}
  RF_APP_HOST: {{ default "" .Values.global.hostname | b64enc | quote }}
  RF_APP_ADMIN: {{ required "\nERROR: admin user not set!\nUpdate secret.rf_app_admin inside chart/values.yaml file." .Values.global.admin | b64enc | quote }}
  RF_APP_ADMIN_PASSWD: {{ required "\nERROR: admin password not set!\nUpdate secret.rf_app_admin_passwd inside chart/values.yaml file." .Values.global.passwd | b64enc | quote }}
  {{- end }}
  {{- with .Values.global.local }}
  RF_STORAGE_TYPE: {{ default "ls"| b64enc | quote }}
  RF_S3_BUCKET: {{ default "" .storage | b64enc | quote }}
  RF_ROLE_ARN: {{ default "" | quote }}
  AWS_ACCESS_KEY_ID: {{ default "" | quote }}
  AWS_SECRET_ACCESS_KEY: {{ default "" | quote }}
  AWS_DEFAULT_REGION: {{ default "" | quote }}
  RF_GS_CREDS: {{ default "" | quote }}
  RF_AZURE_CONNECTION_STRING: {{ default "" | quote }}
  {{- end }}
  {{- with .Values.global.aws }}
  RF_STORAGE_TYPE: {{ default "s3"| b64enc | quote }}
  RF_S3_BUCKET: {{ required "\nERROR: S3 bucket required!\n" .storage | b64enc | quote }}
  RF_ROLE_ARN: {{ default "" .aws_role_arn | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ default "" .aws_access_key_id | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ default "" .aws_secret_access_key | b64enc | quote }}
  AWS_DEFAULT_REGION: {{ default "us-east-1" .region | b64enc | quote }}
  RF_GS_CREDS: {{ default "" | quote }}
  RF_AZURE_CONNECTION_STRING: {{ default "" | quote }}
  {{- end }}
  {{- with .Values.global.gcp }}
  RF_STORAGE_TYPE: {{ default "gs" | b64enc | quote }}
  RF_S3_BUCKET: {{ required "\nERROR: gcloud storage bucket required!\n" .storage | b64enc | quote }}
  RF_ROLE_ARN: {{ default "" | quote }}
  AWS_ACCESS_KEY_ID: {{ default "" .aws_access_key_id | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ default "" .aws_secret_access_key | b64enc | quote }}
  AWS_DEFAULT_REGION: {{ default "us-east-1" .region | b64enc | quote }}
  RF_GS_CREDS: {{ default "" .gs_creds | b64enc | quote }}
  RF_AZURE_CONNECTION_STRING: {{ default "" | quote }}
  {{- end }}
  {{- with .Values.global.azure }}
  RF_STORAGE_TYPE: {{ default "as" | b64enc | quote }}
  RF_S3_BUCKET: {{ required "\nERROR: Azure storage bucket required!\n" .storage | b64enc | quote }}
  RF_ROLE_ARN: {{ default "" | quote }}
  AWS_ACCESS_KEY_ID: {{ default "" .aws_access_key_id | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ default "" .aws_secret_access_key | b64enc | quote }}
  AWS_DEFAULT_REGION: {{ default "us-east-1" .region | b64enc | quote }}
  RF_GS_CREDS: {{ default "" | quote }}
  RF_AZURE_CONNECTION_STRING: {{ default "" .az_connection_string | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.db.auth }}
  DB_URL: {{ printf "mysql+mysqldb://%s:%s@%s:%s/%s?ssl=%s" .Values.global.db.auth.username .Values.global.db.auth.password .Values.global.db.auth.host .Values.global.db.auth.port .Values.global.db.auth.db_name .Values.global.db.auth.db_ssl| b64enc | quote }}
  {{- else }}
  DB_URL: {{ default "mysql+mysqldb://root:RF-123579@mysql/standalone" .Values.global.db_url | b64enc | quote }}
  {{- end }}
  RF_VERBOSE: {{ default "0" .Values.global.rf_verbose| toString | b64enc | quote }}
  KEYCLOAK_JWT_PUB_KEY: {{ default "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt0EwFCzsmzWgn7A8A40hzX1kPHab0WZTmUF8OwHt7fyds6sBiSDPnLIh0BgmXIO2WIrGzARm9dVUeAWI/aUI7qucfgYgW7XSwwz7X/IrX6DExsNZzTLxgIfDJR/WP0fo1vO10BQDAtJxEkX5YvFitBFzg4FLKMZP5inAFM21+jfjD2ufi7NWTyFJR6YCLGFma29XHE75yE76+Xq8eH3DI/8xmrU5hw1Yk5GrABf4KYTijsp+QLQZkEycYvfJEPEMigwnARdp6C3VDp/T8OL1hb2YtrZ4vjZ80azEicQ3ea/R05JK6ikfik2SlC5Rm0Ore0Rh4jB1tI51biVa0smsiwIDAQAB" .Values.global.keycloak_jwt_pub_key | b64enc | quote }}
  KEYCLOAK_CLIENT_ID: {{ default "scanners" | b64enc | quote }}
  KEYCLOAK_REALM: {{ default "customers" | b64enc | quote }}
  KEYCLOAK_SERVICE_ACCOUNT_CLIENT_ID: {{ default "admin-cli" | b64enc | quote }}
  KEYCLOAK_SERVICE_ACCOUNT_CLIENT_SECRET: {{ default "5b97220c-838a-4186-bcdd-8cdb77d0e0f3" .Values.global.keycloak_service_account_client_secret | b64enc | quote }}
  QUAY_TOKEN: {{ default "h3ohDyUwTjZwOgsdw4I2xVwmjCJ3bso3vWWlEPrF" | b64enc | quote }}