apiVersion: v1
kind: ServiceAccount
metadata:
  name: rapidfort
  labels:
    {{- include "rapidfort.labels" . | nindent 4 }}
  annotations: 
    eks.amazonaws.com/role-arn: {{default "rf-role" .Values.secret.aws_role_arn }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end -}}  