{{- if .Values.storageClass.create }}
{{- if and .Values.global.cloud (eq .Values.global.cloud "eks") }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rf-storage-rw
parameters:
  encrypted: "true"
  fsType: ext4
  type: gp3
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
{{- end }}
{{- end }}