rapidfort:
  enabled: true 
  sourceType: git
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/third-party/rapidfort
    branch: main
    path: chart
  helmRepo:
    repoName: "registry1"
    chartName: "rapidfort"
    tag: "1.2.0-bb.1"

  flux: {}

  ingress:
    gateway: ""
  
  objectStorage:

    # -- Access key for connecting to object storage endpoint.
    aws_access_key_id: ""

    # -- Secret key for connecting to object storage endpoint.
    aws_secret_access_key: ""

    # -- Region that bucket is in
    aws_default_region: ""

    # -- Bucket name to use for RapidFort
    s3_bucket: ""
    
    rf_app_admin: ""
    
    rf_app_admin_password: ""
    
    # optional. default set to private-registry
    imagePullSecret: ""
    
    # role arn for connecting to object storage endpoint.
    aws_role_arn: ""

# Big Bang 
domain: bigbang.dev
      
networkPolicies:
  enabled: true

istioOperator:
  enabled: true

istio:
  enabled: true

neuvector:
  enabled: false

kyvernoPolicies:
  enabled: false
  values:
    policies:
      disallow-privileged-containers:
        parameters:
          excludeContainers:
            - iso-master*
            - runner*
      restrict-host-path-mount-pv:
        enabled: true
        validationFailureAction: audit
        parameters:
          # -- List of allowed paths for hostPath volumes to mount
          allow:
            - /tmp
      restrict-host-path-mount:
        enabled: true
        validationFailureAction: audit
        parameters:
          # -- List of allowed paths for hostPath volumes to mount
          allow:
            - /tmp
      restrict-host-path-write:
        enabled: true
        validationFailureAction: audit
        parameters:
          # -- List of allowed paths for hostPath volumes to mount as read/write
          allow:
            - /tmp
      require-non-root-user:
        enabled: true
        validationFailureAction: audit
        parameters:
          excludeContainers:
            - iso-master*
            - runner*
            - vulns-db*
      restrict-capabilities:
        enabled: true
        validationFailureAction: audit
        parameters:
          excludeContainers:
            - iso-master*
      require-non-root-group:
        enabled: true
        validationFailureAction: audit
        parameters:
          excludeContainers:
            - mysql*
            - redis*
            - files-redis*
            - lock-redis*
            - keycloak*
            - runner*
            - iso-master*
            - vulns-db*
gatekeeper:
  enabled: false
  values:
    violations:
      noPrivilegedContainers:
        parameters:
          excludedResources:
          - 'rapidfort/iso-master'
          - 'rapidfort/runner'
      allowedHostFilesystem:
        parameters:
          allowedHostPaths:
          - pathPrefix: /var/run/docker.sock
            readOnly: false
          - pathPrefix: /tmp
            readOnly: false
      volumeTypes:
        parameters:
          excludedResources:
            - 'rapidfort/aggregator-.*'
            - 'rapidfort/backend-.*'
            - 'rapidfort/fileupload-.*'
            - 'rapidfort/isomaster-.*'
            - 'rapidfort/rfscan-.*'
            - 'rapidfort/runner-.*'
            - 'rapidfort/runnerbeat-.*'

# Toggle for Bigbang Core packages set true to install
jaeger:
  enabled: false

kiali:
  enabled: false

clusterAuditor:
  enabled: false

gatekeeper:
  enabled: false

kyverno:
  enabled: false

tempo:
  enabled: false

promtail:
  enabled: false

loki:
  enabled: false

eckOperator:
  enabled: false

elasticsearchKibana:
  enabled: false

fluentbit:
  enabled: false

monitoring:
  enabled: false

grafana:
  enabled: false

twistlock:
  enabled: false


addons:
  argocd:
    enabled: false
  authservice:
    enabled: false
  gitlab:
    enabled: false
  gitlabRunner:
    enabled: false
  anchore:
    enabled: false
  sonarqube:
    enabled: false
  minioOperator:
    enabled: false
  minio:
    enabled: false
  mattermostoperator:
    enabled: false
  mattermost:
    enabled: false
  nexus:
    enabled: false
  velero:
    enabled: false
  keycloak:
    enabled: false
  vault:
    enabled: false
