rapidfort:
  enabled: true 

  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/third-party/rapidfort
    branch: main
    path: chart

  flux: {}

  ingress:
    gateway: ""
  
  objectStorage:

    # -- Access key for connecting to object storage endpoint.
    aws_access_key_id: ""

    # -- Secret key for connecting to object storage endpoint.
    aws_secret_access_key: ""

    # -- Region that bucket is in
    aws_default_region: ""

    # -- Bucket name to use for RapidFort
    s3_bucket: ""

# Big Bang 
domain: bigbang.dev

global:
  # -- This field is used to update the host name in the ingress.
  rf_app_host: ""
  ingressClassName: ""
  allowed_rf_host: "api.rapidfort.com"
  db:
    auth:
      host: "mysql"
      username: "mysql"
      password: "mysql"
      port: "3306"
      database: "standalone"  

networkPolicies:
  enabled: true

istioOperator:
  enabled: true

istio:
  enabled: true

neuvector:
  enabled: false

kyvernoPolicies:
  values:
    policies:
      disallow-privileged-containers:
        parameters:
          excludeContainers:
            - iso-master*
            - runner*
      restrict-host-path-mount-pv:
        enabled: true
        validationFailureAction: audit
        parameters:
          # -- List of allowed paths for hostPath volumes to mount
          allow:
            - /var/run/docker.sock
            - /tmp
      restrict-host-path-mount:
        enabled: true
        validationFailureAction: audit
        parameters:
          # -- List of allowed paths for hostPath volumes to mount
          allow:
            - /var/run/docker.sock
            - /tmp
      restrict-host-path-write:
        enabled: true
        validationFailureAction: audit
        parameters:
          # -- List of allowed paths for hostPath volumes to mount as read/write
          allow:
            - /var/run/docker.sock
            - /tmp

gatekeeper:
  enabled: true
  values:
    violations:
      noPrivilegedContainers:
        parameters:
          excludedResources:
          - 'rapidfort/iso-master'
          - 'rapidfort/runner'
      allowedHostFilesystem:
        parameters:
          allowedHostPaths:
          - pathPrefix: /var/run/docker.sock
            readOnly: false
          - pathPrefix: /tmp
            readOnly: false
      volumeTypes:
        parameters:
          excludedResources:
          - 'rapidfort/iso-master-.*'
          - 'rapidfort/runner-.*'

# Toggle for Bigbang Core packages set true to install
jaeger:
  enabled: false

kiali:
  enabled: false

clusterAuditor:
  enabled: false

gatekeeper:
  enabled: false

kyverno:
  enabled: false

tempo:
  enabled: false

promtail:
  enabled: false

loki:
  enabled: false

eckOperator:
  enabled: false

elasticsearchKibana:
  enabled: false

fluentbit:
  enabled: false

monitoring:
  enabled: false

grafana:
  enabled: false

twistlock:
  enabled: false


addons:
  argocd:
    enabled: false
  authservice:
    enabled: false
  gitlab:
    enabled: false
  gitlabRunner:
    enabled: false
  anchore:
    enabled: false
  sonarqube:
    enabled: false
  minioOperator:
    enabled: false
  minio:
    enabled: false
  mattermostoperator:
    enabled: false
  mattermost:
    enabled: false
  nexus:
    enabled: false
  velero:
    enabled: false
  keycloak:
    enabled: false
  vault:
    enabled: false