rapidfort:
  enabled: true 

  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/third-party/rapidfort
    branch: main
    path: chart

  flux: {}

  ingress:
    gateway: ""
  
  objectStorage:

    # -- Access key for connecting to object storage endpoint.
    aws_access_key_id: ""

    # -- Secret key for connecting to object storage endpoint.
    aws_secret_access_key: ""

    # -- Region that bucket is in
    aws_default_region: ""

    # -- Bucket name to use for RapidFort
    s3_bucket: ""

# Big Bang 
domain: bigbang.dev

networkPolicies:
  enabled: false

istiooperator:
  enabled: true

istio:
  enabled: true

gatekeeper:
  enabled: false

clusterAuditor:
  enabled: false

eckoperator:
  enabled: false

logging:
  enabled: false

fluentbit:
  enabled: false

monitoring:
  enabled: false

jaeger:
  enabled: false

kiali:
  enabled: false

twistlock:
  enabled: false

promtail:
  enabled: false