rapidfort:
  enabled: true 

  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/third-party/rapidfort
    branch: main
    path: chart

  flux: {}

  ingress:
    gateway: ""
  
  objectStorage:

    # -- Access key for connecting to object storage endpoint.
    aws_access_key_id: ""

    # -- Secret key for connecting to object storage endpoint.
    aws_secret_access_key: ""

    # -- Region that bucket is in
    aws_default_region: ""

    # -- Bucket name to use for RapidFort
    s3_bucket: ""

# Big Bang 
domain: bigbang.dev

networkPolicies:
  enabled: true

istiooperator:
  enabled: true

istio:
  enabled: true

gatekeeper:
  enabled: true
  values:
    violations:
      noPrivilegedContainers:
        parameters:
          excludedResources:
          - 'rapidfort/iso-master'
      allowedHostFilesystem:
        parameters:
          allowedHostPaths:
          - pathPrefix: /var/run/docker.sock
            readOnly: false
          - pathPrefix: /tmp
            readOnly: false
      volumeTypes:
        parameters:
          excludedResources:
          - 'rapidfort/iso-master-.*'
          - 'rapidfort/runner-.*'

clusterAuditor:
  enabled: true

eckoperator:
  enabled: false

logging:
  enabled: false

fluentbit:
  enabled: false

# -- This is because integration job in bbci is broken and clusterAuditor fails without monitoring enabled
monitoring:
  enabled: true

jaeger:
  enabled: false

kiali:
  enabled: false

twistlock:
  enabled: false

promtail:
  enabled: false