apiVersion: v2
name: bigbang-rapidfort
description: RapidFort Big Bang Helm Chart
type: application
version: 1.2.5-bb.3
appVersion: 1.1.165
annotations:
  bigbang.dev/upstreamReleaseNotesMarkdown: ""
