{{- if and ( .Values.istio.enabled ) ( .Values.istio.rapidfort.enabled ) }}
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default-rapidfort"
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode | default "PERMISSIVE" }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "mysql-rapidfort"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "redis-rapidfort"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  mtls:
    mode: {{ .Values.istio.mtls.mode | default "PERMISSIVE" }} 
{{ end }}