env:
  vmpool_server_addr: "internal-rf-dev-k8-internal-256088288.us-east-1.elb.amazonaws.com"
  security_group_id: "sg-01d63cd27ae484e2a"
  vpc_subnet_id: "subnet-0c33ba187b6ccffb2"
  redis_host_ha: "rfv-db-redis-cluster-master"
  redis_pwd_ha: "0OmEriiPbb"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-type
          operator: In
          values:
          - storageOptimized

livenessProbe:
  failureThreshold: 3

readinessProbe:
  failureThreshold: 3

pvc:
  image_db: "rf-dev-k8-development-image-db"
  package_analyzer_db: "rf-dev-k8-development-package-analyzer-db"

volumes:
  - name: fuse
    hostPath:
      path: /dev/fuse
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
  - name: imgs-work-dir
    hostPath:
      path: /imgs-work-dir
      type: DirectoryOrCreate
  - name: package-analyzer-db-pvc
    persistentVolumeClaim:
      claimName: "{{ .Values.pvc.package_analyzer_db }}"
  - name: image-db-pvc
    persistentVolumeClaim:
      claimName: "{{ .Values.pvc.image_db }}"
  - name: vulns-db
    hostPath:
      path: /opt/rapidfort/data/iso-master/vulns_db
  # - name: env
  #   configMap:
  #     name: rf-version-info
volumeMounts:
  - name: fuse
    mountPath: "/dev/fuse"
  - name: dockersock
    mountPath: "/var/run/docker.sock"
  - name: imgs-work-dir
    mountPath: "/opt/rapidfort/iso-master/app/imgs_work_dir"
  - name: package-analyzer-db-pvc
    mountPath: "/opt/rapidfort/iso-master/app/package-analyzer-db"
  - name: image-db-pvc
    mountPath: "/opt/rapidfort/iso-master/app/image_db"
  - name: vulns-db
    mountPath: "/opt/rapidfort/iso-master/app/db"
  # - name: env
  #   mountPath: "/opt/rapidfort/.env"

global:
  rf_app_host: "frontrow-dev.rapidfort.io"     

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60
  
securityContext:
  privileged: true
  allowPrivilegeEscalation: true
  capabilities:
    drop:
      - ALL
    add:
      - SYS_ADMIN
      - SYS_PTRACE