env:
  on_premise: 1

secret:
  name: "rf-secret"
  keys:
    - AWS_DEFAULT_REGION
    - DB_URL
    - RF_S3_BUCKET
    - KEYCLOAK_JWT_PUB_KEY
    - KEYCLOAK_REALM
    - KEYCLOAK_CLIENT_ID
    - KEYCLOAK_SERVICE_ACCOUNT_CLIENT_ID
    - KEYCLOAK_SERVICE_ACCOUNT_CLIENT_SECRET
    - ADMIN_ROLE_ID
    - MEMBER_ROLE_ID
    - GUEST_ROLE_ID
    - RF_APP_HOST
    - RF_APP_ADMIN
    - RF_ROLE_ARN
    - DEPLOY_MODE    

keycloak:
  serviceName: keycloak
  
autoscaling:
  enabled: false 
