apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rfapi.fullname" . }}
  labels:
    {{- include "rfapi.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rfapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rfapi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{ if eq .Values.env.rf_debug  true }}
      - name: code
        hostPath:
          path: /root/rapidfort
      {{ end }}  
      serviceAccountName: {{ include "rfapi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init
          image: 274057717848.dkr.ecr.us-east-1.amazonaws.com/init:1.1.0-271e065-19
          command:
            - "/bin/bash"
            - "-c"
            - "until [ $(redis-cli -h {{ .Values.env.redis_host }} -p {{ .Values.env.redis_port }} ping) == 'PONG' ]; do echo redis not ready; sleep 1; done"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ if eq .Values.env.rf_debug  true }}
          workingDir: /root/rapidfort/rfapi
          command: ["/bin/sh", "-c", "sleep infinity"]
          {{ end }}          
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            {{- if eq .Values.env.rf_debug true }}
            - name: code
              mountPath: "/root/rapidfort"
            {{ end }}          
          env:
            - name: "RF_DEBUG"
              value: "{{ .Values.env.rf_debug }}"
            - name: RF_REDIS_HOST_NAME
              value: "{{ .Values.env.redis_host }}"
            - name: RF_REDIS_PORT
              value: "{{ .Values.env.redis_port }}"
            - name: RF_REDIS_PWD
              value: "{{ .Values.env.redis_pwd }}"
          livenessProbe:
            periodSeconds: 30
            initialDelaySeconds: 15
            timeoutSeconds: 10          
            {{- if eq .Values.env.rf_debug true }}
            exec:
              command:
              - /bin/true
            {{ else }}
            httpGet:
              path: /
              port: http
            {{ end }}
          readinessProbe:
            periodSeconds: 30
            initialDelaySeconds: 15
            timeoutSeconds: 10          
            {{- if eq .Values.env.rf_debug true }}
            exec:
              command:
              - /bin/true
            {{ else }}
            httpGet:
              path: /
              port: http
            {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
