{{- if .Values.rapidfort.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: rapidfort
  labels:
    {{- if .Values.istio.enabled }}
    istio-injection: "enabled"
    {{- end }}
    app.kubernetes.io/name: rapidfort
    {{- include "commonLabels" . | nindent 4}}
{{- end }}
