# Default values for iso-master.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 274057717848.dkr.ecr.us-east-1.amazonaws.com/iso-master
  tag: stable
  pullPolicy: Always

env:
  ami_image_id: "ami-06fb837f38439836e"
  debug: off
  s3bucket: "rapidfort"
  vm_scheduler_port: 80
  vm_server_addr: vm-scheduler
  redis_host: redis
  security_group_id: "sg-0cb2f23f1b8da8468"
  vpc_subnet_id: "subnet-0f8c9a907f6bb6c94"
  backend_service_name: "backend"
  vul_redis_host: "redis"
  vul_redis_port: "6379"
  vul_redis_db: 4
  auth_server_base_url: "http://keycloak"
  vul_redis_password: ""
  deployment_mode: "STANDALONE" # this has to be upper case as per the code standard
  control_plane_host: ""
  rf_app_host: ""
  data_plane_host: ""
  aws_default_region: us-east-1
  rf_role_arn: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext:
  fsGroup: 412

securityContext:
  privileged: true
  capabilities:
    add:
    - SYS_ADMIN

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
  hosts:
    - host: 
      paths:
        - /iso-master/.*
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 600m
    memory: 1024Mi

tolerations: []

affinity: {}

nodeSelector: {}

pvc:
  image_db: "image-db-pvc"
  package_analyzer_db: "package-analyzer-db-pvc"

#TODO: use this in template.
livenessProbe:
  periodSeconds: 30
  initialDelaySeconds: 15
  timeoutSeconds: 10
  failureThreshold: 1

readinessProbe:
  periodSeconds: 30
  initialDelaySeconds: 15
  timeoutSeconds: 10
  failureThreshold: 1

secretName: "rf-secret"

initContainer:
  image:
    repository: 274057717848.dkr.ecr.us-east-1.amazonaws.com/rfstub.alp.base
    tag: latest