{{- if and (eq .Values.rapidfort.sourceType "git") (not .Values.offline) .Values.rapidfort.enabled }}
{{- $gitCredsDict := dict
  "name" "rapidfort"
  "packageGitScope" .Values.rapidfort.git
  "rootScope" .
  "releaseName" .Release.Name
}}
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: rapidfort
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: rapidfort
    {{- include "commonLabels" . | nindent 4}}
spec:
  interval: {{ .Values.flux.interval }}
  url: {{ .Values.rapidfort.git.repo }}
  ref:
    {{- include "validRef" .Values.rapidfort.git | nindent 4 }}
  {{ include "gitIgnore" . }}
  {{- include "gitCredsExtended" $gitCredsDict | nindent 2 }}
{{- end }}
