env:
  vmpool_server_addr: "internal-rs-production-vm-scheduler-1013727704.us-east-1.elb.amazonaws.com"
  security_group_id: "sg-0cb2f23f1b8da8468"
  vpc_subnet_id: "subnet-0f8c9a907f6bb6c94"
  redis_host_ha: "rfv-db-redis-cluster-master"
  redis_pwd_ha: "uyTo7TJ0Za"

pvc:
  image_db: "rapidfort-saas-production-image-db"
  package_analyzer_db: "rapidfort-saas-production-package-analyzer-db"

volumes:
  - name: fuse
    hostPath:
      path: /dev/fuse
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
  - name: imgs-work-dir
    hostPath:
      path: /imgs-work-dir
      type: DirectoryOrCreate
  - name: package-analyzer-db-pvc
    persistentVolumeClaim:
      claimName: "{{ .Values.pvc.package_analyzer_db }}"
  - name: image-db-pvc
    persistentVolumeClaim:
      claimName: "{{ .Values.pvc.image_db }}"
  - name: vulns-db
    hostPath:
      path: /opt/rapidfort/data/iso-master/vulns_db
  # - name: env
  #   configMap:
  #     name: rf-version-info
volumeMounts:
  - name: fuse
    mountPath: "/dev/fuse"
  - name: dockersock
    mountPath: "/var/run/docker.sock"
  - name: imgs-work-dir
    mountPath: "/opt/rapidfort/iso-master/app/imgs_work_dir"
  - name: package-analyzer-db-pvc
    mountPath: "/opt/rapidfort/iso-master/app/package-analyzer-db"
  - name: image-db-pvc
    mountPath: "/opt/rapidfort/iso-master/app/image_db"
  - name: vulns-db
    mountPath: "/opt/rapidfort/iso-master/app/db"
  # - name: env
  #   mountPath: "/opt/rapidfort/.env"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-type
          operator: In
          values:
          - storageOptimized

livenessProbe:
  failureThreshold: 3

readinessProbe:
  failureThreshold: 3

global:
  rf_app_host: "frontrow.rapidfort.com"

keycloak:
  serviceName: keycloak-http